theme: jekyll-theme-cayman
title: "Data Mining Lab 2020: The Variational Fair Autoencoder Project"
urls:
  paper: "https://arxiv.org/pdf/1511.00830.pdf"
  slides: "https://github.com/yolomeus/DMLab2020VFAE/tree/gh-pages/slides"